// src/components/layout/Navbar.jsx
import { Fragment } from 'react'
import { Menu, Transition } from '@headlessui/react'
import { 
  Bars3Icon, 
  UserCircleIcon,
  Cog6ToothIcon,
  ArrowRightOnRectangleIcon
} from '@heroicons/react/24/outline'
import { useAuth } from '../../context/useAuth'
import Button from '../ui/Button'

const Navbar = () => {
  const { user, signOut, isAuthenticated, isAdmin } = useAuth()

  const handleSignOut = async () => {
    try {
      await signOut()
      // Redirect will be handled by auth context
    } catch (error) {
      console.error('Error signing out:', error)
    }
  }

  return (
    <nav className="bg-white shadow-sm border-b border-gray-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between h-16">
          {/* Logo and brand */}
          <div className="flex items-center">
            <div className="shrink-0">
              <h1 className="text-xl font-bold text-primary-600">
                Course Platform
              </h1>
            </div>
          </div>

          {/* Desktop navigation */}
          <div className="hidden md:flex md:items-center md:space-x-4">
            {isAuthenticated ? (
              <>
                {/* Navigation links */}
                <a
                  href="/dashboard"
                  className="text-gray-700 hover:text-primary-600 px-3 py-2 rounded-md text-sm font-medium transition-colors"
                >
                  Dashboard
                </a>
                
                {isAdmin && (
                  <>
                    <a
                      href="/admin"
                      className="text-gray-700 hover:text-primary-600 px-3 py-2 rounded-md text-sm font-medium transition-colors"
                    >
                      Admin
                    </a>
                    <a
                      href="/admin/courses"
                      className="text-gray-700 hover:text-primary-600 px-3 py-2 rounded-md text-sm font-medium transition-colors"
                    >
                      Courses
                    </a>
                  </>
                )}

                {/* User menu */}
                <Menu as="div" className="relative ml-3">
                  <div>
                    <Menu.Button className="flex text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500">
                      <span className="sr-only">Open user menu</span>
                      {user?.user_metadata?.avatar_url ? (
                        <img
                          className="h-8 w-8 rounded-full"
                          src={user.user_metadata.avatar_url}
                          alt={user.user_metadata.full_name || 'User'}
                        />
                      ) : (
                        <UserCircleIcon className="h-8 w-8 text-gray-400" />
                      )}
                    </Menu.Button>
                  </div>
                  <Transition
                    as={Fragment}
                    enter="transition ease-out duration-100"
                    enterFrom="transform opacity-0 scale-95"
                    enterTo="transform opacity-100 scale-100"
                    leave="transition ease-in duration-75"
                    leaveFrom="transform opacity-100 scale-100"
                    leaveTo="transform opacity-0 scale-95"
                  >
                    <Menu.Items className="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none z-50">
                      <div className="px-4 py-2 border-b border-gray-100">
                        <p className="text-sm font-medium text-gray-900">
                          {user?.user_metadata?.full_name || 'User'}
                        </p>
                        <p className="text-sm text-gray-500">
                          {user?.email}
                        </p>
                        {isAdmin && (
                          <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-primary-100 text-primary-800 mt-1">
                            Admin
                          </span>
                        )}
                      </div>
                      
                      <Menu.Item>
                        {({ active }) => (
                          <a
                            href="/profile"
                            className={`${
                              active ? 'bg-gray-100' : ''
                            } flex items-center px-4 py-2 text-sm text-gray-700`}
                          >
                            <UserCircleIcon className="mr-3 h-4 w-4" />
                            Profile
                          </a>
                        )}
                      </Menu.Item>
                      
                      <Menu.Item>
                        {({ active }) => (
                          <a
                            href="/settings"
                            className={`${
                              active ? 'bg-gray-100' : ''
                            } flex items-center px-4 py-2 text-sm text-gray-700`}
                          >
                            <Cog6ToothIcon className="mr-3 h-4 w-4" />
                            Settings
                          </a>
                        )}
                      </Menu.Item>
                      
                      <Menu.Item>
                        {({ active }) => (
                          <button
                            onClick={handleSignOut}
                            className={`${
                              active ? 'bg-gray-100' : ''
                            } flex items-center w-full text-left px-4 py-2 text-sm text-gray-700`}
                          >
                            <ArrowRightOnRectangleIcon className="mr-3 h-4 w-4" />
                            Sign out
                          </button>
                        )}
                      </Menu.Item>
                    </Menu.Items>
                  </Transition>
                </Menu>
              </>
            ) : (
              <div className="flex items-center space-x-4">
                <Button variant="outline" size="sm">
                  Login
                </Button>
                <Button size="sm">
                  Sign Up
                </Button>
              </div>
            )}
          </div>

          {/* Mobile menu button */}
          <div className="md:hidden flex items-center">
            <button
              type="button"
              className="text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-primary-500 p-2 rounded-md"
              aria-controls="mobile-menu"
              aria-expanded="false"
            >
              <span className="sr-only">Open main menu</span>
              <Bars3Icon className="block h-6 w-6" aria-hidden="true" />
            </button>
          </div>
        </div>
      </div>

      {/* Mobile menu (you can expand this with state management) */}
      <div className="md:hidden" id="mobile-menu">
        {/* Mobile menu content would go here */}
      </div>
    </nav>
  )
}

export default Navbar

// src/components/Navbar.vue
<script setup>
import { computed } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { useAuth } from '../composables/useAuth';
import VButton from './VButton.vue';

const router = useRouter();
const route = useRoute();

// Use real authentication
const { currentUser, isLoggedIn, isAdmin, isUser, logout } = useAuth();

const handleSignIn = () => {
  router.push('/signin');
};

const handleSignOut = () => {
  logout();
  router.push('/');
};

const goToDashboard = () => {
  if (isAdmin.value) {
    router.push('/admin');
  } else {
    router.push('/dashboard');
  }
};
</script>

<template>
  <header class="fixed inset-x-0 top-0 z-50">
    <nav class="legendary-nav mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8" aria-label="Global">
      <div class="flex items-center">
        <router-link to="/" class="flex items-center space-x-3 group">
          <span class="sr-only">Creator to CEO</span>
          <div class="logo-container">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="logo-icon">
              <path stroke-linecap="round" stroke-linejoin="round" d="M4.26 10.147a60.438 60.438 0 0 0-.491 6.347A48.62 48.62 0 0 1 12 20.904a48.62 48.62 0 0 1 8.232-4.41 60.46 60.46 0 0 0-.491-6.347m-15.482 0a50.636 50.636 0 0 0-2.658-.813A59.906 59.906 0 0 1 12 3.493a59.903 59.903 0 0 1 10.399 5.84c-.896.248-1.783.52-2.658.814m-15.482 0A50.717 50.717 0 0 1 12 13.489a50.702 50.702 0 0 1 7.74-3.342M6.75 15a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Zm0 0v-3.675A55.378 55.378 0 0 1 12 8.443m-7.007 11.55A5.981 5.981 0 0 0 6.75 15.75v-1.5" />
            </svg>
          </div>
          <span class="brand-text">Creator2CEO</span>
        </router-link>
      </div>
      
      <div class="hidden md:flex md:gap-x-1 lg:gap-x-2">
        <router-link to="/" class="legendary-link">
          Home
        </router-link>
        <router-link to="/courses" class="legendary-link">
          Courses
        </router-link>
        
        <!-- Show Dashboard link only when logged in -->
        <router-link 
          v-if="isAdmin" 
          to="/admin" 
          class="legendary-link"
        >
          Admin Dashboard
        </router-link>
        <router-link 
          v-else-if="isUser" 
          to="/dashboard" 
          class="legendary-link"
        >
          My Dashboard
        </router-link>
      </div>
      
      <div class="flex items-center gap-x-3">
        <!-- Not Logged In -->
        <template v-if="!isLoggedIn">
          <VButton 
            size="sm"
            variant="ghost"
            @click="router.push('/login')"
          >
            Sign In
          </VButton>
          <VButton 
            size="sm"
            @click="handleSignIn"
          >
            Get Started
          </VButton>
        </template>
        
        <!-- Logged In - User Menu -->
        <template v-else>
          <button
            @click="goToDashboard"
            class="flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-gray-100 transition-colors duration-200"
          >
            <img 
              :src="currentUser.avatar" 
              :alt="currentUser.name"
              class="w-8 h-8 rounded-full"
            />
            <span class="text-sm font-medium text-gray-700 hidden lg:block">
              {{ currentUser.name }}
            </span>
          </button>
          <VButton 
            size="sm"
            variant="ghost"
            @click="handleSignOut"
          >
            Sign Out
          </VButton>
        </template>
      </div>
    </nav>
  </header>
</template>

<style scoped>
/* Legendary Navigation */
.legendary-nav {
  background: white;
  border-bottom: 1px solid #e5e7eb;
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
  transition: all 0.3s ease;
}

/* Logo Container */
.logo-container {
  position: relative;
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, var(--color-primary-600), var(--color-primary-500));
  border-radius: 12px;
  box-shadow: 
    0 4px 12px rgba(59, 130, 246, 0.25),
    0 0 0 3px rgba(59, 130, 246, 0.1);
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

.logo-container::before {
  content: '';
  position: absolute;
  inset: 0;
  background: linear-gradient(to bottom, rgba(255, 255, 255, 0.3), transparent);
  border-radius: 12px;
  pointer-events: none;
}

.logo-container:hover {
  transform: translateY(-2px) rotate(-5deg);
  box-shadow: 
    0 8px 20px rgba(59, 130, 246, 0.35),
    0 0 0 3px rgba(59, 130, 246, 0.15);
}

.logo-icon {
  width: 24px;
  height: 24px;
  color: white;
  position: relative;
  z-index: 1;
}

/* Brand Text */
.brand-text {
  font-size: 1.25rem;
  font-weight: 800;
  background: linear-gradient(135deg, #1f2937, #374151);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  letter-spacing: -0.02em;
  transition: all 0.3s ease;
}

.brand-text:hover {
  background: linear-gradient(135deg, var(--color-primary-600), var(--color-primary-500));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

/* Legendary Links */
.legendary-link {
  position: relative;
  padding: 8px 12px;
  border-radius: 10px;
  transition: all 0.3s ease;
  color: #374151;
  text-decoration: none;
}

.legendary-link::after {
  content: '';
  position: absolute;
  bottom: 2px;
  left: 12px;
  right: 12px;
  height: 2px;
  background: var(--color-primary-600);
  border-radius: 2px;
  transform: scaleX(0);
  transition: transform 0.3s ease;
}

.legendary-link:hover::after {
  transform: scaleX(1);
}
</style>
